FROM python:3.12-slim

WORKDIR /opt/ml/processing

COPY src/ ./src/
COPY configs/ ./configs/
COPY pyproject.toml .

RUN pip install --no-cache-dir \
    pandas numpy scikit-learn xgboost pyarrow scipy \
    joblib boto3 python-dotenv pyyaml

ENTRYPOINT ["python", "-m"]
